faktaoklimatu/web-core

_config.global.yml
Jekyll apparently uses the exclude list when watching for changes in files (e.g. when running `jekyll serve`). Since files in the `.cache` directory may change after each build, Jekyll is prone to fall into an endless loop of rebuilding the site over and over again. See, for instance, jekyll/jekyll#736.
=> Exclude .cache directory in Jekyll config

assets/_scss/core_design.scss, assets/js/main.js
The fixed position of the navbar poses some issues when jumping to a heading since the heading is obscured by the navbar at the top of the screen. In place of hackish solution involving negative spacing, we may now use the [`scroll-padding`](http://mdn.io/scroll-padding) property.
Resolves faktaoklimatu/web-cz#751
(Migrated from faktaoklimatu/web-cz#758.)
=> Fix headings spacing in presence of navbar

_includes/header.html
Allow for social media links to explainers to display the cover image as a preview for the page via Open Graph tags.
=> Use explainer cover image as OG preview

_includes/preview-block.html, _includes/preview-box.html, assets/_scss/index.scss
Allow for explainers to be referenced in preview boxes (via`preview-box.html`).
Related: faktaoklimatu/web-cz#781
=> Allow explainers in preview box

.gitignore, .travis.global.yml, Dockerfile, Makefile, _config.global.yml, _includes/preview-block.html, _layouts/explainer.html, _plugins/glyph-replacement.rb, assets/_scss/explainer.scss, utils/convert-cover.sh
This PR sets up Makefile to generate resized version of cover images. For consistency, these cover images are now assumed to be next to its .md file. The resized versions are used for the preview box and for the actual page on mobile.
Fixes #36.
=> Generate resized version of explainer covers (for preview boxes and more)

_includes/preview-block-small.html, assets/_scss/search.scss, assets/js/search.js, search.json
This CL makes several small improvements:
- the [X] button is now fully opaque,
- resizing window when search results are open hides the results (so that resizing works well),
- search.json got simplified (and now supports arbitrary many special pages, even with custom images).
=> Further search fixes

_includes/figure.html, assets/_scss/infographic.scss
Currently not ideal (the text is probably too small) but the interaction with mentioning the source is not trivial.
Though, I think that this solution is sufficient for now. If so, I'll create an issue on the matter.
For preview, see corals explainer at https://cz-fakta-o-klimatu--preview-explainer-korali-eor1y6go.web.app
=> Add option to have captions in figures

Gemfile, Gemfile.lock, _config.global.yml, _includes/header.html
Render math formulae written in TeX syntax into MathML and HTML+CSS during compile time. This is done using [katex-ruby](https://github.com/glebm/katex-ruby) via the [kramdown-math-katex plugin](https://github.com/kramdown/math-katex).
Known issues:
- katex-ruby uses an older version of KaTeX (0.11.0 [August 2019] vs. 0.13.2 [April 2021]) – no substantial differences, though.
- Problems with double-escaping ampersands. Not an issues for the basic use case.
=> Add support for math formulae

search.json
This PR fixes the issue with html containing unescaped latex math - jsonify filter makes sure this does not break the json syntax.
=> Fix search.json - jsonify all fields

_plugins/space-replacement.rb
In case the `page` object has no `output` property, an error gets logged but execution continues as though nothing has happened. We need to skip processing the document in case an error like this occurs.
=> Fix crash in space replacement plugin

_plugins/space-replacement.rb
It is `next` not `continue`.
Fixes #69
=> Correct Ruby keyword for skipping an iteration

_includes/navigation.html, assets/js/search.js
In Safari, the onblur handler for the search input field failed to identify that the element gaining focus is the search result list. Thus, the handler closed the search result list before the click event got processed and the navigation to the search target did not proceed.
This PR adds tabindex=0 to the search results list so that this element gets populated to event.relatedTarget. This fixes the check that the element gains focus.
Fixes #59
=> Fix search in Safari

assets/js/search.js
This fixes a glitch on Android that opening virtual keyboard (which changes the height of the page) closes the searchbox.
Fixes #78
=> Keep searchbox open when window heigth changes

Gemfile, Gemfile.lock, config-templates/_config.global.yml
Closes #18 
I have found this plugin that cleans up the generated HTML. The generated code looks good. Let me know if you like it as well.
I have compared generated `index.html` to make sure it does not break something and quickly went through a bunch of pages as well. But please take a look with your trained eye.
Thanks!
=> Adding jekyll-tidy to cleanup generated html

_includes/figure.html
Allow specifying filename for a mobile version of a figure. This will be displayed on screens smaller than 768px in width (medium breakpoint in Bootstrap).
Resolves #88
@mukrop Does this look OK to you?
=> Add support for responsive figures

Gemfile, Gemfile.lock
Temporarily add webrick as an explicit dependency. Fixes build on Fedora 34.
@mgrabovsky, @jankrcal, mohli by ste prosim vyskusat, ze aj build na starsom prostredi funguje OK, aby som to touto zmenou nerozbil ostatnym?
=> Fix build with Ruby 3+

assets/_scss/core_design.scss, assets/_scss/infographic.scss
This changes unifies the assumed height of navbar across two occurrences and thereby solves
* navbar obscuring the TOC (#51) and
* heading being located lower than expected on the screen.
Resolves #51
=> Factor navbar height out to a variable

_includes/footer.html, _includes/newsletter.html, _includes/scripts.html, assets/_scss/index.scss, assets/js/newsletter.js, deploy-templates/firebase.json
* Add a modal and script loading Ecomail form.
* CSP violations still need to be addressed.
* Temporary preview available at https://cz-fakta-o-klimatu--preview-newsletter-ecomail-nncd42bv.web.app/
=> Transition newsletter to Ecomail

Gemfile, Gemfile.lock, _config.global.yml, _plugins/html-beautify.rb
Closes #81 
I don't like that jekyll-tidy allows only to exclude files instead of including specific ones. So I got inspired by it and wrote a small plugin of our own.
I've compared all the generated files before and after (including the tree itself). Only HTML files are affected. I also checked the content of the files. It all seems fine. The beautifier will break inline JS if we ever want to do that but that would be discovered during dev.
=> #81: Replacing tidy with local plugin

_plugins/space-replacement.rb
* Use Unicode glyphs in place of HTML entities. This is functionally equivalent and semantically more correct –  we can now use `\s` to match on the space (if we ever need to).
* Add extra checks for word boundaries to avoid false positives.
* Add ‘m’ and ‘km’ to list of units.
=> Improve space replacement plugin

_plugins/space-replacement.rb
Fix bug that caused brekage in HTML attributes, e.g. the space in `class="mt-3 mb-3"` would be replaced as well.
Fixes #96
=> Fix space replacement plugin

_layouts/infographic.html
Specifying the whole srcset so that browser can decide what resolution to load. I've changed the href to the highest resolution as I'd assume you want to best quality if you want to download it.
I've tested it in chrome with different resolutions. I could not quite get it to load 600, it would load always at least 1200. I think that's fine.
=> #28 infographics resolution optimization

_config.global.yml, _includes/figure.html, _includes/header.html, _includes/js/fancybox.js, _includes/scripts.html, _layouts/infographic.html, assets/js/fancybox.js
Resolves #76 
Adding fancybox. I decided to use version 3.7.2 (opposed to 4.alpha4) because of the download button and stability. The transition to version 4 would not be all that hard if we decide to do so later.
I've added the translation for SK and CS (please check).
I've introduced a new global object `fakta` where we can put information from our templating.
Please let me know if there is another place where the lightbox should go.
Thanks.
=> Adding fancybox to figures and infographics

_layouts/infographic.html
Resolves #106.
Details: Chrome on Android with Lite mode enabled proactively decides the infographic image is partially covered and thus will not be loaded to save data bandwidth. Setting loading mode to `eager` prevents this behavior.
=> Prevent infographics from lazy loading

_includes/figure.html, _includes/js/fancybox.js, _layouts/infographic.html
I only enable lightbox on non-mobile browsers. The check is apparently done testing agent for certain strings. I could also do dynamically based on viewport if you find it nonsufficient.
=> Disabling fancybox on mobile devices.

_includes/scripts.html, assets/js/fancybox.js
Currently, it was included as an inline script violating CSP rules.
=> Move FancyBox JS to JS folder

assets/_scss/index.scss, assets/_scss/search.scss, assets/js/search.js
This PR addresses a few minor issues in search:
- fixes missing thumbnails on mobile (a new style introduced in #168 in search.scss was unintentionally applied only to desktop)
- tweaks styling of the overlay text on mobile (making it smaller to better fit the small size of the thumbnail; especially important for the longer "Podcast 2050" overlay)
- makes podcast open in a new window/tab from search (to make the behavior consistent with usages in boxes and elsewhere) - podcasts are detected by the URL being absolute, starting with a URL scheme like "https://"
=> Fix missing thumbnails in mobile search

_plugins/filter-truncatewords-html.rb, _plugins/podcast-redirect.rb
Make the `get_url` filter a bit more resilient and return `nil` if the input is `nil`. This prevents unreadable tracebacks when the input is not a document as expected.
\+ Remove import of `nokogumbo` in favour of `nokogiri` (see sparklemotion/nokogiri#2205).
=> Add check to get_url filter

_layouts/topic.html, assets/_scss/topic.scss
This PR adds a bit of polish & visual unity to Q&A sections on the pages of topics:
- trims down borders
- turns black into light-gray
- animates the chevron (via css)
=> Polish styling of Q&A for topics

_includes/preview-block.html, _layouts/survey.html, _layouts/topic.html, assets/_scss/core_design.scss, assets/_scss/index.scss
This PR further unifies the design of cards of individual products (like studies, surveys, etc.).
Notably
- for studies, their images are now used in the card;
- for surveys, the "Survey: " prefix is added automatically to the title.
As an unrelated minor fix, smooth scrolling is configured for the whole site (try it on the TOC in any explainer or on any other link within a page).
=> Unify design of product cards

_includes/preview-block-without-link.html, _includes/preview-block.html, assets/_scss/core_design.scss, utils/test.rb
This PR introduces a test that enforces there is no build error log (`DIV.build-error`) in the resulting HTML files.
It also adds first few instances of such error logs in the templates:
- when an unknown slug is used for a preview block;
- when an unknown layout is used for a preview block.
In the future, this technique will be used for more types of sanity checks in the code.
=> Add a test checking for build errors

_includes/footer.html, _includes/preview-block.html, _includes/preview-blocks.html, _layouts/dataset.html, assets/_scss/core_design.scss, assets/_scss/index.scss, assets/_scss/topic.scss
This PR achieves a few changes:
1. shows preview boxes at 90% width, instead of 100% (which needs injecting one more div container)
2. improves the mobile layout of the home page significantly; notably this includes:
- decreasing the huge font sizes for the home page (so far only for mobile)
- compressing the top area with our claim
- making the top buttons fit on one row (slightly questionable as the font is now relatively small)
- putting the tabs on one row (needs small font but I really want this)
- making the footer readable
4. generic minor adjustments of spacing on topic pages.
Especially for the point 2, corresponding changes are needed in the language version of the site.
=> Improve (mobile) layout of topic pages and the home page

_layouts/topic.html, assets/_scss/core_design.scss, assets/js/navbar.js
This PR fixes a minor bug in how the two navbars merge on mobile.
The interplay of popping up the small title and counting with its height (before it had any height at all) was too complex. With this PR now:
- the small title is always part of the layout, it's only invisible until the secondary navbar becomes stuck;
- the size of the invisible title is roughly compensated by a negative margin (and a few other minor spacing tweaks here and there);
- the primary title becomes relative with a higher z-index so that it is not covered by the secondary navbar.
=> [Topic pages] Fix flickr on mobile navbar

_includes/related.html, assets/_scss/core_design.scss, assets/_scss/index.scss
This PR fixes a minor css bug in expander lists and makes more use of this concept (in related.html).
The only remaining uses of (old) preview-blocks.html are now related to old topic pages (index.md and tag.html).
=> Further unify use of preview blocks

deploy-templates/firebase.json
Google analytics changed server domains from `https://www.google-analytics.com` to `https://region1.google-analytics.com`. To account for more regions, I'm relaxing the policy for GA and GTM to `https://*.google-analytics.com` and `https://*.googletagmanager.com` respectively,
=> Fix CSP (content security policy)

_includes/footer.html, assets/_scss/core_design.scss, assets/_scss/index.scss
This PR recovers CSS code deleted (by mistake) in https://github.com/faktaoklimatu/web-core/pull/183/files.
Furthermore, it incorporates minor feedback:
- adds "Support-us" button into the footer (mobile only),
- removes intro buttons custom styling (as they anyway don't fit on one line anymore),
- enlarges navbar fonts and spacing for mobile (for better tappability).
=> Minor fixes to homepage design

.travis.global.yml, Makefile
This PR makes Makefile rules for generating infographics assets more robust.
Previously, only lack of `/assets/generated/foo.pdf` triggered the script that generated all of these files:
- `/assets/generated/foo.pdf`
- `/assets/generated/foo.svg`
- `/assets/generated/foo_600.png`
- `/assets/generated/foo_1200.png`
- `/assets/generated/foo_1920.png`
- `/assets/generated/foo_6000.png`
After this change, lack of any of these files triggers the script.
As a minor unrelated fix, `/assets/episodes ` gets removed from travis cache because this folder is not used any more in the build process.
=> More robust Makefile rules for /assets/generated

_includes/related.html
This PR fixes a minor bug in the "related" tiles.
Before this PR, some content (occurring in multiple related subsections) could show up several times. After this PR, every piece of content appears at most once.
Fixes #206.
=> Remove duplicates from related items

_includes/expander.html, assets/_scss/figure.scss
This commit also makes large expander titles a bit smaller based on feedback from Katka.
=> Remove expander functionality for expaned figures

.gitignore, Makefile, _includes/header.html, _layouts/publication.html, _layouts/topic.html, utils/convert-illustration.sh, utils/convert-infographic.sh, utils/convert-svg.sh
This PR restructures Makefiles to convert all svg illustrations for individual pages into pngs as well. These pngs are then used for og:image tags.
This PR also fixes og:description in two ways:
- adds support for page.perex (used by explainers and publications),
- trims Markdown from description (used by topics) by 'markdownify | trim_html' filters.
=> Convert illustrations into PNGs (for og:image)

_includes/author-internal.html, _includes/author.html, _includes/preview-block-small.html, _includes/preview-block-without-link.html, _layouts/explainer.html, assets/_scss/explainer.scss
This PR makes two changes:
- removes "explainer" labels (except for small preview boxes in search results) and allows custom types where we want to stress specialty of some long / complex text;
- improves authorship section for explainers. It is backwards compatible to still allow the previous free-form unstructered text.
In the process, this PR refactors authors.html a bit - allowing more flexibility (that is needed by a wider range of applications in existing explainers in web-cz). After this PR, each line in authors correspond to one author / group of authors in a similar role. It can be specified by one of the following:
- `id`: [string id of an internal member]
- `name`: [string expressing the name of an external author]
- `ids`: [array of string ids of internal authors]
- …
=> Explainer authors and types

_layouts/explainer.html, assets/_scss/explainer.scss
This PR adds simple support for last-update date for explainers.
This is useful for better transparency around our texts, especially when making some larger changes.
=> Support declaring last update for an explainer

_includes/header.html
Use the `page` object instead of the undefined `item`.
=> Fix object reference in og:image link construction

_includes/header.html, _includes/preview-block-small.html, _includes/preview-block-without-link.html, search.json
This PR makes use of `search_image` for social media.
To this end:
- `search_image` and `search_type` are renamed to `preview_image` and `preview_type` as they are anyway also used for in-site preview blocks;
- existence in search index is decoupled from `preview_type` a new boolean property `include_in_search` is introduced for the pages collection instead.
=> Use preview image for og:image

_plugins/glossary-tag.rb
This PR makes sure we don't overlook mistakes in <glossary> tags such as a wrong id.
=> Abort build on error in <glossary>

assets/_scss/explainer.scss
This PR fixes layout for updated publication dates on mobile. It makes tags wrap on another line if all the content does not fit on one line. To this end, it replaces the middot separator with more spacing (as it is not clear to CSS if it splits to multiple lines).
=> Fix explainer cover (with updated date) on mobile

_includes/author-internal.html
This PR supports structured authorship for explainers without linking to an internal "Team" page. This is useful for the SK/EN sites.
=> Allow no link for internal authors

.gitignore
This PR makes ignore .DS_Store files created by Mac Finder when browsing through the files of the repo.
=> Ignore Mac .DS_Store

assets/_scss/core_design.scss
This makes it apparent that elements with titles and tooltips can be hovered over to reveal an explanation or other kind of information.
=> Highlight text elements with titles

_includes/figure.html
This PR allows figures from an include to override their folder (and
thus have them only once in the repo).
=> Allow overriding folder for figures

_includes/authors.html
Hide minor role label if it is the same as for the previous person. For example, if there are two consulting roles, hide the label for the second one.
[Preview](https://cz-fakta-o-klimatu--preview-minor-role-dupl-4xuiuoh0.web.app/explainery/zdravi-pudy-degradace)
=> Hide duplicate minor roles

.travis.global.yml, Makefile
- Opt-in to the v2 of Travis deployment scripts for better Ruby
compatibility. v1 scripts use Ruby 2 which seems to be in conflict with
our Gem dependencies.
- Do not trigger build for the second or third time during deployment – it is a waste of time and does not belong to this phase.
=> Fix deployment step

Gemfile, Gemfile.lock
Bump webrick dependency in order to include a fix for [CVE-2024-47220](https://nvd.nist.gov/vuln/detail/CVE-2024-47220).
=> Bump webrick dependency due to a CVE

_config.global.yml, _includes/expander.html, assets/_scss/figure.scss
This for most cases adds an additional layer of <p> markup. I've tested most existing instances, nothing breaks. (as last child <p> has no margins in our styling).
=> Markdownify expander title
