_includes/figure.html, _includes/preview-block.html, _layouts/explainer.html, _layouts/infographic.html, _layouts/study.html, _layouts/survey.html, _layouts/tag.html, assets/_scss/core_design.scss, assets/_scss/explainer.scss, assets/_scss/index.scss
This PR improves the layout for explainers and makes sure they can get displayed from elsewhere in the web.
=> Explainers - finishing improvements

_includes/preview-block.html, _layouts/explainer.html, assets/_scss/explainer.scss
Adds missing license info for explainers.
=> Explainers: expansible license info

_layouts/tag.html, assets/_scss/tags.scss
=> Fix broken tag page header layout on mobile

Makefile, assets/_scss/search.scss, search.json
Minor fix for raw html appearing in search snippets for some pages.
Fixes #43
=> Minor search improvements

_config.global.yml
This decreases the attack surface to one single CDN.
=> Unify CDN links to cloudflare.com

_includes/footer.html
Requires locally translated string.
=> Add footer link to GDPR

assets/_scss/index.scss, assets/_scss/news.scss
A few minor tweaks to the style sheets. See commits for details.
=> Visual style tweaks

_includes/footer.html, _includes/infographic-dataset-sidebar.html, _includes/preview-box.html, _layouts/dataset.html, _layouts/empty.html, _layouts/explainer.html, _layouts/infographic.html, _layouts/single-section-page.html, _layouts/study.html, _layouts/survey.html, _layouts/tag.html
I made multiple small changes, resolving multiple (often old) issues. Can someone please do a review?
As the issues are unrelated to each other, I suggest reviewing by individual commits, not changed files. Individual commits also contain details and reasons on changes.
For testing, see a related PR in web-cz.
=> Small html improvements

assets/_scss/core_design.scss
Related: faktaoklimatu/web-cz#871
=> Add CSS class for ions in chem. formulas

assets/_scss/core_design.scss
Related: faktaoklimatu/web-cz#887
=> Add class for inline bullet lists

Makefile, utils/validate-json.rb
Check that the generated index for site search is a valid JSON file in `make check`.
Related: #83
=> Validate generated search index

assets/_scss/core_design.scss
Fixes #102, requires https://github.com/faktaoklimatu/web-cz/pull/924 merged.
=> Remove btn-outline primary.

_layouts/infographic.html
Fixes #90 introduced in a clash between 352fd4ec and 50257300.
=> Fix empty TOC still visible.

Dockerfile, Makefile, README.md
* Optimise Dockerfile to reduce intermediate layers.
* Update Dockerfile metadata.
* Mount volume with `:z` option to ensure correct SELinux labels.
* Change SELinux type mentioned in readme to a more general, safer one.
* Make WEBrick listen on `0.0.0.0` to avoid networking problems   on some systems.
=> Tweak container deployment

_includes/navigation.html
=> Localise "Search" string

_includes/navigation.html, assets/js/search.js
=> Unify search localization string IDs

_includes/navigation.html, assets/_scss/core_design.scss
* Use correct logotype instead of favicon + text.
=> Adjust navbar logo

_config.global.yml, _includes/figure.html
Resolves #13 (though without strict variables due to a long-standing bug).
=> Enable strict filters

_includes/lead-in-figure.html, assets/_scss/figure.scss, assets/_scss/infographic.scss, assets/css/main.scss
This is a thing we use in faktaoklimatu/web-cz#1026.
=> Add code and styles for lead-in figure

_layouts/topic.html, assets/_scss/topic.scss
This PR restyles a bit the dasboards for topic pages.
As a minor change, it fixes a bug in QAs styling (when the question spans multiple lines, it looked slightly broken).
=> Restyle topic dashboard

_layouts/topic.html, assets/_scss/topic.scss
This PR restyles intros of topic pages to match it to the desired design.
=> [Topic pages] Restyle intro

_includes/footer.html
Localise one left over string in the new footer.
=> Localise a string in footer

assets/_scss/core_design.scss, assets/_scss/index.scss
This PR makes a trivial change to allow reusing one css class in a new context.
=> Rename a css class for better clarity

_layouts/survey.html
This PR makes minor adjustment to the `survey` layout needed by https://github.com/faktaoklimatu/web-cz/pull/1106.
=> Markdownify survey intro and adjust margins

_includes/navigation.html, assets/_scss/core_design.scss, assets/_scss/index.scss, assets/_scss/search.scss, assets/js/navbar.js
This PR adds support for banners in navbar for ongoing campaigns, etc.
=> Banner support

assets/_scss/index.scss
This PR increases margins for logos (to conform with prescribed protected areas around logos).
=> Adjust spacing of logos

_includes/figure.html
This PR allows to specify an image class for the figure include.
=> Allow image-class for figure include

_includes/footer.html
This PR adds an option to add contact links to the footer.
=> Add a contact link to the footer (and to the copyright identification label)

Makefile, _config.global.yml, _includes/preview-block-small.html, _includes/preview-block-without-link.html, _layouts/publication.html, assets/_scss/publication.scss, assets/_scss/tags.scss, assets/css/main.scss
This commit adds a new layout for publications of Fakta o klimatu.
=> Create new layout for own publications

_includes/header.html, _includes/preview-block-small.html, _includes/preview-block-without-link.html
Each survey is responsible for using the picture on its own page, if desired.
=> Add support for preview pictures for surveys

assets/js/main.js
* Allow content authors to use Bootstrap tooltips for enhanced user experience, especially on mobile devices. This is useful, for instance, when hovering over/touching an icon for an explanation of its meaning.
* Remove unnecessary timeout in main script.
=> Enable Bootstrap tooltips

_config.global.yml, _includes/footer.html, _includes/infographic-dataset-sidebar.html, assets/_scss/infographic.scss
- Update Font Awesome to 6.5.1 for new X and Threads icons.
- Update Twitter → X logo.
- Include link to Threads in the footer.
=> Update social icons – Twitter/X, Threads

_layouts/publication.html, assets/_scss/publication.scss
This PR allows customizing text colors in publication covers.
=> Customize text (and button) color for publication covers

.travis.global.yml, Dockerfile
Update the version of Ubuntu in Travis and Docker one notch (to 22.04) in order to fix build issues due to outdated Ruby version and related issues.
=> Update Ubuntu to 22.04

assets/_scss/colors.scss, assets/_scss/table.scss, assets/css/main.scss
Refresh the design of tables slightly -- make them lighter, declutter visually.
Related: faktaoklimatu/web-cz#1358
=> Tables refresh

_includes/footer.html
This PR adds possibility to add "a we're hiring link to the footer".
=> Add we're hiring link to the footer

assets/_scss/index.scss
=> Adjust wide logo height slightly

_includes/scripts.html
This PR adds a possibility for local javascript files. These files are added to each generated HTML page (that includes scripts.html).
=> Add possibility for local javascript files

feed.xml
=> Add updated date to entries in RSS feed
